### ISSUE TITLE
Problems with newlines

### ISSUE THREAD

**Issue by nadar** [deanblackborough/php-quill-renderer#101]
Dear @deanblackborough thanks for the greate package. We do have an issue with newlines and breaks - its not rendered like the html direct output.

<img width="451" alt="bildschirmfoto 2018-09-10 um 21 23 08" src="https://user-images.githubusercontent.com/3417221/45319301-bf309780-b53f-11e8-9177-65a9191ea16e.png">

The text above the HR renders the direct "html" output from quill. The output below the hr renders the deltas trough your library:

```php
$quill = new Render($json);
return $quill->render();
```

Here is the delta code:

```json
{
  "ops": [
    {
      "insert": "Hallo"
    },
    {
      "attributes": {
        "header": 1
      },
      "insert": "\n"
    },
    {
      "insert": "\nDas ist ein normaler Text:\n\n"
    },
    {
      "attributes": {
        "bold": true
      },
      "insert": "Test: Eintrag"
    },
    {
      "insert": "\n"
    },
    {
      "attributes": {
        "bold": true
      },
      "insert": "Test: Zwei"
    },
    {
      "insert": "\n\nhttps://heartbeat.gmbh\n\n\n"
    }
  ]
}
```

Do you have any idea what we are doing wrong - or its a problem of the library? It seems to be a very common use case.

**Comment by nadar** [comment]
Its seems like the empty 

```
{
      "insert": "\n"
    },
```

Is not parsed / rendered. Like it would skip the content.

here is also the rendered html content:

original:

```
<h1>Hallo</h1>
<p><br></p>
<p>Das ist ein normaler Text:</p>
<p><br></p>
<p><strong>Test: Eintrag</strong></p>
<p><strong>Test: Zwei</strong></p>
<p><br></p>
<p>https://heartbeat.gmbh</p>
<p><br></p>
<p><br></p> 
```

rendered trough delta:

```
<h1>Hallo</h1><br />
<p>Das ist ein normaler Text:</p><br />
<p><strong>Test: Eintrag</strong><strong>Test: Zwei</strong></p><br />
<p>https://heartbeat.gmbh</p><br />
<p></p><br />
```

**Comment by nadar** [comment]
If there is something i can help, let me know.

**Comment by deanblackborough** [comment]
@nadar This is should be fixed in v3.14.2, newline only inserts are no longer ignored. I added a test using your delta above, DBlackborough\Quill\Tests\Api\BugTest::testNewlineOnlyInsertsIgnored(). 

Testing using your delta I didn't get the second issue I mentioned, so, for now, I am going to assume this issue is closed. 

Again, thank you for the bug report.

**Comment by deanblackborough** [comment]
@nadar I'll have another look at this, cheers again.

**Comment by deanblackborough** [comment]
Closing for now, no follow-on issues have been raised relating to new lines. A newline issue was fixed in v3.14.3 which is after I reopened this ticket so until additional issues are found I'm going to assume this is working as I intended. :)

**Comment by nadar** [comment]
I think the issue above still persist, but its maybe also how you are handling the html output, if you like to have the same output as quill html generates it would be wrong. I assume the summary i made here https://github.com/nadar/quill-delta-parser/issues/3#issuecomment-433221132 is very clear about this.

Closing the issue is fine i guess :-)
